### ISSUE TITLE
[Week 2] Flicks App Complete - Review My App

### ISSUE THREAD

**Issue by cthompson527** [cthompson527/TopCinema#4]
My app is complete after the second week of class. Please review. /cc @codepathreview

**Comment by codepathreview** [comment]
:+1: Nice work! The point of this homework was to get familiar with two common forms of navigation in iOS (push and tab bar). It also provided a chance to extend your Flicks app in new ways.

### Some small comments:
- Good job using `UIScrollView` in `Details View Controller`. But there's a small issue. With some movies having long review, the scroll view isn't tall enough to show all the text like that:
  <img width="312" alt="screen shot 2016-02-07 at 4 25 07 pm" src="https://cloud.githubusercontent.com/assets/7917093/12871653/6dfb17c2-cdb7-11e5-9677-cf7f4da8e70a.png">

Tip: You can use `UITextView` to display the overview. 
- Well done implementing `now playing tab` and `top rated tab` with the cool icons :star: 
- Good job customizing the navigation bar.

We have a detailed [Project 2 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_2_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
